[versions]
agp = "8.8.0"

android-compileSdk = "35"
android-minSdk = "33"
android-targetSdk = "34"
androidx-activityCompose = "1.10.0"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.0"
androidx-core-ktx = "1.15.0"
androidx-espresso-core = "3.6.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
compose-plugin = "1.6.11"
junit = "4.13.2"
kotlin = "2.0.20"

ktor = "2.3.12"
logback = "1.5.6"

gson = "2.11.0"

koin = "3.6.0-wasm-alpha2"
navigation = "2.8.6"
compose = "1.7.7"

lifecycle = "2.9.0-alpha09"

coroutines = "1.8.1"
kotlinBom = "1.9.0"
retrofit = "2.11.0"
okhttp = "4.12.0"
mockk = "1.13.4"
assertj = "3.26.0"
activityKtx = "1.10.0"

mqtt = "1.2.5"
composeMaterial3 = "1.3.1"
junitJupiter = "5.10.1" # or your desired version

#Server:
#kotlin = "1.9.22"
mysql = "8.0.33"
#coroutines = "1.7.3"
#mqtt = "1.2.5"
#ktor = "2.1.0"
#logback = "1.5.3"
#commons = "file:///home/vladimir/projects/IoT/commons/build/libs/commons.jar"
postgres = "42.7.3"
hibernate = "6.1.0.Final"
hibernate-ehcache = "5.6.15.Final"
ehcache = "3.10.8"
jcache = "1.1.1"
jaxb-api = "2.3.1" #Ehcache relies on JAXB for parsing XML configuration
jaxb-impl = "4.0.5"
jaxb-runtime = "4.0.2"  # Use the same version for both api and runtime
jaxb-runtime-old = "2.3.1"

jakarta-jaxb-api = "4.0.2"
jakarta-activation-api = "2.1.3"

infinispan-core = "15.0.10.Final"
infinispan-hibernate-cache = "15.0.10.Final"
infinispan-hibernate-cache-v62 = "15.0.10.Final"
hibernate-cache-commons = "15.0.10.Final"
#jakarta-cache-api = "1.1.1"  # Latest version compatible with Jakarta EE
javax-cache-api = "1.1.1"

mapstruct = "1.6.0.Beta1"
serializationJson = "1.7.1"
dagger = "2.55"
#mockk = "1.13.11"
h2 = "2.2.224"
testcontainers = "1.19.0"
datastoreCoreAndroid = "1.1.2"
#junitJupiter = "5.9.0"

#maps = "18.1.0"

##maplibre = "9.5.0" # Use the latest stable version available
#maplibre = "11.3.0" # Use the latest stable version available

realm = "2.3.0"


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
#c = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-server-tests = { module = "io.ktor:ktor-server-tests-jvm", version.ref = "ktor" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

koinAndroid = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
coreKtx = { module = "androidx.core:core-ktx", version = "1.13.0" }
lifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }



okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
kotlinBom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBom" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }

mqtt = { group = "org.eclipse.paho", name = "org.eclipse.paho.client.mqttv3", version.ref = "mqtt" }
composeMaterial3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

composeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }

#Server:
#kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
mysql-connector-java = { module = "mysql:mysql-connector-java", version.ref = "mysql" }
#coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
#gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
paho-mqtt = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "mqtt" }
#ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
#ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson", version.ref = "ktor" }
ktor-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx-jvm", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-cors = { module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
#No longer needed since we are using KMM: commons = { module = "commons", version.ref = "commons" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
hibernate-core = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }
hibernate-entitymanager = { module = "org.hibernate:hibernate-entitymanager", version = "6.0.0.Alpha7" }
#ehcache = { module = "net.sf.ehcache:ehcache", version = "2.10.6" }
ehcache = { module = "org.ehcache:ehcache", version.ref = "ehcache" }
jcache = { module = "javax.cache:cache-api", version.ref = "jcache" }
hibernate-jcache = { module = "org.hibernate.orm:hibernate-jcache", version.ref = "hibernate" }  # Add this line
hibernate-ehcache = { module = "org.hibernate:hibernate-ehcache", version.ref = "hibernate-ehcache" }
jaxb-api = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb-impl" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb-runtime" }
jaxb-runtime-old = { module = "javax.xml.bind:jaxb-api", version.ref = "jaxb-runtime-old" }


jakarta-jaxb-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-jaxb-api" }
jakarta-activation-api = { module = "jakarta.activation:jakarta.activation-api", version.ref = "jakarta-activation-api" }
#jakarta-cache-api = { module = "jakarta.cache:jakarta.cache-api", version.ref = "jakarta-cache-api" }
javax-cache-api = { module = "javax.cache:cache-api", version.ref = "javax-cache-api" }

# Infinispan dependencies
#infinispan-hibernate-cache = { module = "org.infinispan:infinispan-hibernate-cache-spi", version.ref = "infinispan" }
infinispan-hibernate-cache = { module = "org.infinispan:infinispan-hibernate-cache-v62", version.ref = "infinispan-hibernate-cache-v62" }
infinispan-hibernate-cache-commons = { module = "org.infinispan:infinispan-hibernate-cache-commons", version.ref = "hibernate-cache-commons" }

infinispan-core = { module = "org.infinispan:infinispan-core", version.ref = "infinispan-core" }


#hibernate-ehcache = { module = "org.hibernate:hibernate-ehcache", version = "5.4.12.Final" }
javax-persistence = { module = "javax.persistence:javax.persistence-api", version = "2.2" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
#ktor-server-tests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }


#maplibreGl = { group = "org.maplibre.gl", name = "android-sdk", version.ref = "maplibre" }
#maplibreSdkExtensions = { group = "com.mapbox.mapboxsdk", name = "mapbox-sdk-extensions", version = "10.0.0" }
accompanistPermissions = { group = "com.google.accompanist", name = "accompanist-permissions", version = "0.20.0" }
androidx-datastore-core-android = { group = "androidx.datastore", name = "datastore-core-android", version.ref = "datastoreCoreAndroid" }

realm = { module = "io.realm.kotlin:library-base", version.ref = "realm" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }
