name: Android CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle (with cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug
        run: ./gradlew assembleDebug --stacktrace

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Lint (Android)
        run: ./gradlew lintDebug

      #- name: Detekt
      #  run: ./gradlew detekt

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: composeApp-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk
 
